# HW4 Problem 2


## Import Libraries


In [0]:
import numpy as np
import skimage.measure
from scipy import signal

## Define Function


In [0]:
def maxpooling2d(input_mat, s):

  if (s > input_mat.shape[0]):
    return []
  output_width = (int)(np.ceil((input_mat.shape[0] /s ) ))
  output_length = (int)(np.ceil((input_mat.shape[1] /s ) ))

  output_mat = np.zeros((output_width, output_length))

  for i in np.arange(output_width):
    for j in np.arange(output_length):
      for x in np.arange(s):
        for y in np.arange(s): 
          if(x + i * s < input_mat.shape[0] and y + j * s  < input_mat.shape[1]):
            output_mat[i][j] = max(output_mat[i][j], input_mat[x + i * s][y + j * s])
  return output_mat

## Test Cases


In [0]:
input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array(
                     [[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)


expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
