<a href="https://colab.research.google.com/github/wc6255/CAP-4630/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CAP 4630 Homework 1







#Defining Compatible Matrices
Two matrices being compatible for matrix multiplication are defined as the following: 

Let $A$ be a matrix with $a$ rows and $b$ columns.

Let $X$ be a matrix with $x$ rows and $y$ columns.

$A$ and $B$ are compatible if and only if:

$\quad b=x$

That is, the number of columns in $A$ is the same as the number of rows in $b$. 

#Matrix Multiplication Function 
The multiply_matrices functions takes in a $k$-length list of matrices as input and outputs the product of all of the matrices if a matrix $M_{i}$ is compatible with $M_{i+1}$ for all matrices in the list:

$\quad{M_{1}, M_{2}, ... M_{k}}$

The output is an $m\ x\ n$ matrix where ${m}$ is the number of rows in $M_{1}$ and ${n}$ is the number of columns in $M_{k}$.


In [0]:
import numpy as np
def multiply_matrices (matrices):
    product = matrices[0]
    i = 0
    j = len(matrices)
    while i < j - 1:
        try:
            product = np.matmul(product, matrices[i + 1])
        except:
            print("Exception: Invalid Matrix Pair: Matrices", i, "& ", i + 1)
            return
        i = i + 1
    print(product)
    return

# Test Cases

$\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}*
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}$

In [155]:
x = np.array([[1, 2],[3, 4]], dtype = np.float64)
y = np.array([[5, 6],[7, 8]], dtype = np.float64)
z = np.array([[5, 6],[7, 8]], dtype = np.float64)
lists = [x, y, z]
multiply_matrices(lists)


[[249. 290.]
 [565. 658.]]


$\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}$

In [158]:
i = 0
lists = []
while i < 10:
     lists.append(np.array([[1, 2],[3, 4]], dtype = np.float64))
     i = i + 1
multiply_matrices(lists)

[[ 4783807.  6972050.]
 [10458075. 15241882.]]


$\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}*
\begin{bmatrix}
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}*
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}$

In [172]:
x = np.array([[1, 2],[3, 4]], dtype = np.float64)
y = np.array([[5, 6],[7, 8], [9,10]], dtype = np.float64)
z = np.array([[5, 6],[7, 8]], dtype = np.float64)
lists = [x, y, z]
multiply_matrices(lists)

Exception: Invalid Matrix Pair: Matrices 0 &  1


$\begin{bmatrix}
1.3 & 2\\
3 & 4\\
5.5 & 6
\end{bmatrix}*
\begin{bmatrix}
5.5 & 6\\
7 & 8
\end{bmatrix}*
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}$

In [174]:
x = np.array([[1.3, 2],[3, 4], [5.5,6]], dtype = np.float64)
y = np.array([[5.5, 6],[7, 8]], dtype = np.float64)
z = np.array([[5, 6],[7, 8]], dtype = np.float64)
lists = [x, y, z]
multiply_matrices(lists)

[[ 272.35  317.3 ]
 [ 572.5   667.  ]
 [ 928.25 1081.5 ]]


$\begin{bmatrix}
1 \\
2
\end{bmatrix}*
\begin{bmatrix}
3 & 4
\end{bmatrix}
$

In [163]:
x = np.array([[1], [2]])
y = np.array([[3,4]])
lists = [x, y]
multiply_matrices(lists)

[[3 4]
 [6 8]]


$\begin{bmatrix}
3 & 4
\end{bmatrix}*
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$

In [164]:
x = np.array([[1], [2]])
y = np.array([[3,4]])
lists = [y, x]
multiply_matrices(lists)

[[11]]


$\begin{bmatrix}
1
\end{bmatrix}*
\begin{bmatrix}
3 & 4
\end{bmatrix}
$

In [170]:
x = np.array([[1]])
y = np.array([[3, 4]])
lists = [x, y]
multiply_matrices(lists)

[[3 4]]
